# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67c279f9c7c7c1b80cae73ca012db072f45fa7102ba769a5e8f5ccc7588eafc6a226bf6598a0b1fb90b420f043141dcd0fa3cc8780037dc4273881561958f4ab

test:
  secret_key_base: db6c9d17cb021f44dc659c5d2f082a7db93810023d80fac6a6b4324ef778d8843ccb527349c9302d550ef3d7b16e8c4e56ac629ee34804ebefaee9446dae596b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
